//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuppliesReport.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Docs\\Data\\Данные.xlsx")]
        public string ExcelDataFilePath {
            get {
                return ((string)(this["ExcelDataFilePath"]));
            }
            set {
                this["ExcelDataFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Docs\\Templates\\")]
        public string TemplatesDirectoryPath {
            get {
                return ((string)(this["TemplatesDirectoryPath"]));
            }
            set {
                this["TemplatesDirectoryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Шаблон Акт ликвидации.docx")]
        public string TemplateActEliminationFileName {
            get {
                return ((string)(this["TemplateActEliminationFileName"]));
            }
            set {
                this["TemplateActEliminationFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Шаблон Акт проверки и осмотра.docx")]
        public string TemplateActInspectionFileName {
            get {
                return ((string)(this["TemplateActInspectionFileName"]));
            }
            set {
                this["TemplateActInspectionFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Шаблон Акт списания.docx")]
        public string TemplateActWritingOffFileName {
            get {
                return ((string)(this["TemplateActWritingOffFileName"]));
            }
            set {
                this["TemplateActWritingOffFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Шаблон Приказ о списании.docx")]
        public string TemplateOrderWritingOffFileName {
            get {
                return ((string)(this["TemplateOrderWritingOffFileName"]));
            }
            set {
                this["TemplateOrderWritingOffFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Шаблон Протокол заседания комиссии.docx")]
        public string TemplateProtocolSessionFileName {
            get {
                return ((string)(this["TemplateProtocolSessionFileName"]));
            }
            set {
                this["TemplateProtocolSessionFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Docs\\")]
        public string OutputDirectoryPath {
            get {
                return ((string)(this["OutputDirectoryPath"]));
            }
            set {
                this["OutputDirectoryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" Инв. № ")]
        public string WritingoffInventorynameHelpString {
            get {
                return ((string)(this["WritingoffInventorynameHelpString"]));
            }
            set {
                this["WritingoffInventorynameHelpString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Шаблон Отчет.docx")]
        public string TemplateReportFileName {
            get {
                return ((string)(this["TemplateReportFileName"]));
            }
            set {
                this["TemplateReportFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Шаблон Снятие с довольствия.docx")]
        public string TemplateSupplyPopFileName {
            get {
                return ((string)(this["TemplateSupplyPopFileName"]));
            }
            set {
                this["TemplateSupplyPopFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Шаблон Постановка на довольствие.docx")]
        public string TemplateSupplyPushFileName {
            get {
                return ((string)(this["TemplateSupplyPushFileName"]));
            }
            set {
                this["TemplateSupplyPushFileName"] = value;
            }
        }
    }
}
