//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuppliesReport.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FormContext : DbContext
    {
        public FormContext()
            : base("name=FormContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DO_PRIZ> DO_PRIZ { get; set; }
        public DbSet<DUP> DUP { get; set; }
        public DbSet<GORODA> GORODA { get; set; }
        public DbSet<KN_P> KN_P { get; set; }
        public DbSet<kom> kom { get; set; }
        public DbSet<LOG_P> LOG_P { get; set; }
        public DbSet<NA_UCHETE> NA_UCHETE { get; set; }
        public DbSet<NET_N_VB> NET_N_VB { get; set; }
        public DbSet<NVOZVR> NVOZVR { get; set; }
        public DbSet<OBRAZ> OBRAZ { get; set; }
        public DbSet<OPERAT_SPR> OPERAT_SPR { get; set; }
        public DbSet<PRIZ> PRIZ { get; set; }
        public DbSet<RAILROAD> RAILROAD { get; set; }
        public DbSet<REZH_KOM> REZH_KOM { get; set; }
        public DbSet<rezhim> rezhim { get; set; }
        public DbSet<RVK> RVK { get; set; }
        public DbSet<SEM_POL> SEM_POL { get; set; }
        public DbSet<SPEC> SPEC { get; set; }
        public DbSet<SUD> SUD { get; set; }
        public DbSet<TABLE1> TABLE1 { get; set; }
        public DbSet<V_OKRUG> V_OKRUG { get; set; }
        public DbSet<VID_VS> VID_VS { get; set; }
        public DbSet<VID_VS_FOR_PRIC> VID_VS_FOR_PRIC { get; set; }
        public DbSet<ZVAN> ZVAN { get; set; }
    }
}
