//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuppliesReport.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KN_P
    {
        public int ID { get; set; }
        public string FAM { get; set; }
        public string IM { get; set; }
        public string OTCH { get; set; }
        public string D_ROD { get; set; }
        public string RVK { get; set; }
        public string KUDA { get; set; }
        public string KTO { get; set; }
        public string IGNORE { get; set; }
    }
}
