//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuppliesReport.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NA_UCHETE
    {
        public int ID { get; set; }
        public string NAME { get; set; }
    }
}
