//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuppliesReport.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NVOZVR
    {
        public int ID { get; set; }
        public string FAM { get; set; }
        public string IM { get; set; }
        public string OTCH { get; set; }
        public Nullable<System.DateTime> D_ROD { get; set; }
        public string RVK { get; set; }
        public string PRICH { get; set; }
        public string PRIM { get; set; }
        public Nullable<System.DateTime> D_UBIT { get; set; }
        public Nullable<int> OLD_KOD { get; set; }
    }
}
