//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuppliesReport.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERAT_SPR
    {
        public int ID { get; set; }
        public Nullable<int> DOSTAVLENO { get; set; }
        public Nullable<int> VOZVRASHENO { get; set; }
        public Nullable<int> VOZ_NGM { get; set; }
        public Nullable<int> VOZ_DOPOBSL { get; set; }
        public Nullable<int> VOZ_PNZ { get; set; }
        public Nullable<int> VOZ_VUD { get; set; }
        public Nullable<int> VOZ_SEM_OBS { get; set; }
        public Nullable<int> SOCH { get; set; }
        public Nullable<int> UVOLN { get; set; }
        public Nullable<int> NA_OSP { get; set; }
        public Nullable<int> DOST_V_POSL_SUT { get; set; }
        public Nullable<int> OTPR_V_POSL_SUT { get; set; }
        public Nullable<int> OTPR_VSEGO { get; set; }
        public Nullable<int> O_VVS { get; set; }
        public Nullable<int> O_VDV { get; set; }
        public Nullable<int> O_VMF { get; set; }
        public Nullable<int> O_KV { get; set; }
        public Nullable<int> O_12_GU_MO { get; set; }
        public Nullable<int> O_SIR { get; set; }
        public Nullable<int> O_MCHS { get; set; }
        public Nullable<int> O_ZHDV { get; set; }
        public Nullable<int> O_VV { get; set; }
        public Nullable<int> O_PV { get; set; }
        public Nullable<int> O_PP { get; set; }
        public Nullable<int> O_RVSN { get; set; }
        public Nullable<int> O_SV { get; set; }
        public Nullable<int> O_SV_SIBVO { get; set; }
        public Nullable<int> O_SSSI { get; set; }
        public Nullable<int> O_CP { get; set; }
        public Nullable<int> O_CHSS { get; set; }
        public Nullable<System.DateTime> D_SPRAV { get; set; }
        public Nullable<System.TimeSpan> T_SPRAV { get; set; }
        public Nullable<int> NA_OSP_SUD { get; set; }
        public Nullable<int> OTPR_SUD { get; set; }
        public Nullable<int> SOCH_SUD { get; set; }
    }
}
